apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sxcms-data
    component: stastix-cms-app
  name: sxcms-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi