--- 
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: sastixcms
  region: us-east-2

nodeGroups:
  - name: ng1-persistence
    instanceType: m5.large
    desiredCapacity: 1  
    privateNetworking: true
    availabilityZones: ["us-east-2c"]

  - name: ng2-workers
    instanceType: m5.large
    minSize: 0
    maxSize: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true

