apiVersion: v1
kind: Service
metadata:
  labels:
    app: management-center
  name: management-center
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: management-center
