apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
data:
  init.sql: |-
    CREATE DATABASE `sastix_cms_docker` /*!40100 DEFAULT CHARACTER SET utf8 */;
    GRANT ALL PRIVILEGES ON *.* TO 'sastixcms'@'%';
