apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.hazelcast.com/schema/config
                http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
      <management-center enabled="true" update-interval="2">http://management-center:8080/hazelcast-mancenter</management-center>
      <network>
        <join>
          <multicast enabled="false"/>
          <kubernetes enabled="true">
            <namespace>default</namespace>
            <service-name>hazelcast</service-name>
         </kubernetes>
        </join>
      </network>
    </hazelcast>
