apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../1.docker/docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_PASSWORD
          value: sastixcms
        - name: MYSQL_ROOT_PASSWORD
          value: sastixcms
        - name: MYSQL_USER
          value: sastixcms
        image: mariadb:10
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: db-claim1
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
status: {}
