version: '3'

services:
  cms:
    image: buluba89/cms
    restart: always
    environment:
      JAVA_EXTRA_ARGS: "-Dspring.profiles.active=production,docker -Dhazelcast.config.client.enabled=true -Dhazelcast.config.client.address=hazelcast"
      SASTIX_CMS_VOLUME: /opt/sastixcms
      SASTIX_CMS_MYSQL_URL: jdbc:mysql://db:3306/sastix_cms_docker
      SASTIX_CMS_MYSQL_USERNAME: sastixcms
      SASTIX_CMS_MYSQL_PASSWORD: sastixcms
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - cms-data:/opt/sastixcms
    depends_on:
      - db
      - hazelcast
    ports:
      - "9082:9082"

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sastixcms
      MYSQL_PASSWORD: sastixcms
      MYSQL_USER: sastixcms
    volumes:
      - db-data:/var/lib/mysql
      - ${PWD}/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  hazelcast:
    image: hazelcast/hazelcast:3.11.2
    ports:
      - "5701:5701"

#  adminer:
#    image: adminer
#    restart: always

volumes:
  cms-data:
  db-data:

