storage:
  storageClassName: efs

ingress:
  enabled: true

autoscaling:
  enabled: true


mariadb:
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: alpha.eksctl.io/nodegroup-name
                  operator: In
                  values:
                    - ng1-persistence
