storage:
  storageClassName: efs

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

autoscaling:
  enabled: true

monitoring:
  operator: false

mariadb:
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: alpha.eksctl.io/nodegroup-name
                  operator: In
                  values:
                    - ng1-persistence
