dependencies:
  - name: mariadb
    repository: "https://kubernetes-charts.storage.googleapis.com"
    version: "5.5.3"
  - name: hazelcast
    repository: "https://hazelcast.github.io/charts/"
    version: "1.1.2"