apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sastix-cms.fullname" . }}-secret
  annotations:
      "helm.sh/resource-policy": no-upgrade-existing
  labels:
      app: {{ template "sastix-cms.name" . }}
      chart: {{ template "sastix-cms.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  password: {{ randAlphaNum 15 | b64enc | quote }}
  user: YWRtaW4K # admin
