{{ if $.Values.ingress.enabled | default false}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ toYaml . | indent 4 }}
  {{ end }}
  name: {{ template "sastix-cms.fullname" . }}-ingress
  labels:
    app:  {{ template "sastix-cms.name" . }}
    chart:  {{ template "sastix-cms.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{ end }}
spec:
  rules:
  - host: {{ $.Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "sastix-cms.fullname" . }}
          servicePort: http
{{ end }}