{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "sastix-cms.fullname" . }}
  labels:
    app: {{ template "sastix-cms.name" . }}
    chart: {{ template "sastix-cms.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "sastix-cms.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "sastix-cms.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}