{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sastix-cms.serviceAccountName" . }}
  labels:
    app: {{ template "sastix-cms.name" . }}
    chart: {{ template "sastix-cms.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end -}}